douban/urls.py
from django.contrib import admin
from django.urls import path,include
from django.http import HttpResponse

from moive_top250 import views

urlpatterns = [
    path('robots.txt/', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    path('admin/', admin.site.urls),
    path('',views.index),
    path('top250/',include('moive_top250.urls')),
]

moive_top250/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

app_name='douban'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('moive/<int:movie_id>',views.moive_info,name='moive')
]

moive_top250/models.py
from django.db import models

# Create your models here.

class douban_top250(models.Model):
    serial_number=models.IntegerField()
    movie_name=models.CharField(max_length=255)
    introduce=models.CharField(max_length=255)
    star=models.FloatField(max_length=12)
    evaluate=models.CharField(max_length=255)
    describe=models.CharField(max_length=255)
    datetime=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.movie_name

moive_top250/views.py
from django.shortcuts import render,render_to_response
from django.http import HttpResponse

from . import models
# Create your views here.

def render404(request):
    return HttpResponse("404")

def render500(request):
    return HttpResponse("500")

def index(request):
    moives = models.douban_top250.objects.all()
    page=request.GET.get('page')
    if page==None:
        page=1
        return render(request, 'html/index.html', {'moives': moives[:25],'page':int(page)})
    else:
        return render(request,'html/index.html',{'moives':moives[(int(page)-1)*25:(int(page)-1)*25+25],'page':int(page)})




def moive_info(request,movie_id):
    moive=models.douban_top250.objects.get(pk=movie_id)
    return render(request,'html/moive.html',{'moive':moive})

moive_top250/templates/html/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>TOP 250</title>
    <script type="text/javascript" language="javascript" src="{% static "js/Chart.min.js" %}"></script>
    <script type="text/javascript" language="javascript" src="{% static "js/jquery.js" %}"></script>
    <script type="text/javascript" language="javascript" src="{% static "js/index.js" %}"></script>
    <script type="text/javascript" language="javascript" src="{% static "js/moment-with-locales.js" %}"></script>
    <script type="text/javascript" language="javascript" src="{% static "js/vue.js" %}"></script>
    <link rel="SHORTCUT ICON" href="{% static "image/favicon.ico" %}"/>
    <link rel="stylesheet" href="{% static "css/index.css" %}">
</head>
<body>
<form method="get" action="">
    <table>
        {% for moive in moives %}
            <tr>
                <td>
                    <a href="{% url "douban:moive" moive.id %}">
                        {{ moive.serial_number }}
                    </a>
                </td>
                <td>
                    <a href="{% url "douban:moive" movie_id=moive.id %}">
                        {{ moive.movie_name }}
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <div>
        {% if page == 1 %}
            <button type="button" onclick="next_page({{ page }})" >下一页</button>
        {% elif page < 10 %}
            <button type="button" onclick="last_page({{ page }})" >上一页</button>
            <button type="button" onclick="next_page({{ page }})" >下一页</button>
        {% else %}
            <button type="button" onclick="last_page({{ page }})" >上一页</button>
        {% endif %}
    </div>
</form>
</body>
</html>

moive_top250/templates/html/moive.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{{ moive.movie_name }}</title>
    <link rel="SHORTCUT ICON" href="{% static "image/favicon.ico" %}"/>
    <script type="text/javascript" language="javascript" src="{% static "js/Chart.min.js" %}"></script>
    <script type="text/javascript" language="javascript" src="{% static "js/jquery.js" %}"></script>
    <script type="text/javascript" language="javascript" src="{% static "js/index.js" %}"></script>
    <script type="text/javascript" language="javascript" src="{% static "js/moment-with-locales.js" %}"></script>
    <script type="text/javascript" language="javascript" src="{% static "js/vue.js" %}"></script>
</head>
<body>
<h1>{{ moive.movie_name }}</h1>
<p>排名:{{ moive.serial_number }}</p>
<p>演员信息：{{ moive.introduce }}</p>
<p>星级：{{ moive.star }}</p>
<p>评价人数：{{ moive.evaluate }}</p>
<p>评价：{{ moive.describe }}</p>
<button type="button" onclick="returnhome()">返回</button>
</body>
</html>